on:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        # File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version, .tool-versions.
        # If node-version and node-version-file are both provided the action will use version from node-version.
        node-version-file: '.nvmrc'
    - run: npm install
    - run: npm run release --dry-run
